import AboutUs from "@/components/Pages/Home/About-Us";
import Faq from "@/components/Pages/Home/faqold";
import HeroSection from "@/components/Pages/Home/HeroSection";
import HomePricing from "@/components/Pages/Home/HomePricing";
import MyValues from "@/components/Pages/Home/MyValues";
import RecentBlogs from "@/components/Pages/Home/RecentBlogs";
import Review from "@/components/Pages/Home/Review";
import ChatModal from "@/components/Pages/Home/ChatModal";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "E-Clinic - Medical Website",
  description: "Generated by create next app",
};

const MainPage = () => {
  return (
    <> 
      <HeroSection />
      <MyValues />
      <AboutUs />
      <HomePricing />
      <Review />
     <ChatModal/>
      <Faq />
      <RecentBlogs />
    </>
  );
};

export default MainPage;
